export const MenuItems=[
    {
        title:'About',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Event',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Program',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Contact',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Login',
        url:'#',
        cName:'nav-links'
    }
]